<<<<<<< Updated upstream
# Generated by Django 4.0.2 on 2022-02-24 04:28
=======
# Generated by Django 4.0.2 on 2022-03-03 05:08
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=200)),
                ('displayName', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('profileImage', models.CharField(max_length=200)),
<<<<<<< Updated upstream
=======
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InboxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
>>>>>>> Stashed changes
            ],
            options={
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
<<<<<<< Updated upstream
            name='LoginInformationModel',
            fields=[
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'db_table': 'LoginInformation',
            },
=======
            name='PostModel',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('origin', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('contentType', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
                ('categories', models.CharField(max_length=200)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('published', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(max_length=200)),
                ('unlisted', models.BooleanField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='socialdistribution.authormodel')),
            ],
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_context', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('object', models.CharField(max_length=200)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='socialdistribution.authormodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='socialdistribution.authormodel')),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('accept', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='socialdistribution.authormodel')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='socialdistribution.authormodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('post', models.CharField(default='SOME STRING', max_length=200)),
                ('comment', models.CharField(max_length=2000)),
                ('contentType', models.CharField(default='text/markdown', max_length=200)),
                ('published', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='socialdistribution.authormodel')),
            ],
>>>>>>> Stashed changes
        ),
    ]
