# Generated by Django 4.0.2 on 2022-03-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='mysite/img', verbose_name='profile_image'),
        ),
    ]
