# Generated by Django 4.0.2 on 2022-03-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='count',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='', verbose_name='profile_image'),
        ),
    ]
