# Generated by Django 4.0.2 on 2022-02-24 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsSrcModel',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('post', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FollowersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InboxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='authormodel',
            name='username',
        ),
        migrations.AlterModelTable(
            name='authormodel',
            table=None,
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('contentType', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=2000)),
                ('categories', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('published', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(max_length=200)),
                ('unlisted', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.authormodel', verbose_name='post')),
            ],
        ),
        migrations.CreateModel(
            name='LikedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at_context', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('object', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.authormodel', verbose_name='liked')),
            ],
        ),
        migrations.CreateModel(
            name='FollowRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.followersmodel', verbose_name='follower')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.authormodel', verbose_name='followee')),
            ],
        ),
        migrations.AddField(
            model_name='followersmodel',
            name='items',
            field=models.ManyToManyField(to='socialdistribution.AuthorModel'),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=2000)),
                ('contentType', models.CharField(max_length=200)),
                ('published', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.authormodel', verbose_name='comment')),
                ('commentsSrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialdistribution.commentssrcmodel', verbose_name='comments')),
            ],
        ),
    ]
