# Generated by Django 4.0.2 on 2022-03-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='commentsSrc',
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='post',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.DeleteModel(
            name='CommentsSrcModel',
        ),
    ]
