# Generated by Django 4.0.2 on 2022-02-24 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0002_commentssrcmodel_followersmodel_inboxmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='socialdistribution.authormodel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='commentsSrc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='socialdistribution.commentssrcmodel'),
        ),
        migrations.AlterField(
            model_name='followrequestmodel',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='socialdistribution.followersmodel'),
        ),
        migrations.AlterField(
            model_name='followrequestmodel',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followee', to='socialdistribution.authormodel'),
        ),
        migrations.AlterField(
            model_name='likedmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='socialdistribution.authormodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='socialdistribution.authormodel'),
        ),
    ]
