# Generated by Django 4.0.2 on 2022-03-03 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0002_likemodel_delete_likedmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequestmodel',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='socialdistribution.authormodel'),
        ),
    ]
