# Generated by Django 4.0.2 on 2022-03-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0002_alter_authormodel_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='profileImage',
            field=models.ImageField(null=True, upload_to='', verbose_name='profile_image'),
        ),
    ]
