# Generated by Django 4.0.2 on 2022-03-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0003_alter_followrequestmodel_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='followrequestmodel',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
