# Generated by Django 4.0.2 on 2022-02-25 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0003_alter_commentmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='socialdistribution.authormodel'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='origin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='source',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
