# Generated by Django 4.0.2 on 2022-02-25 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialdistribution', '0004_alter_postmodel_author_alter_postmodel_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='socialdistribution.authormodel'),
        ),
    ]
